name: Run Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Use Node.js 21.x
              uses: actions/setup-node@v3
              with:
                  node-version: 21.x
            - run: pnpm ci
            - run: pnpm run build --if-present
            - run: pnpm test
            - run: pnpm run lint
